version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: GerenciadorLivro.API/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1q2w3e4r@#$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./dbdata:/var/opt/mssql/data